# Config file for all WorkstationCommands commands
# Here, you can enable or disable each command and manage their aliases.

# Layout Reference
# <command>.enabled: Whether the command should be enabled.  If not specified, it defaults to false.
# <command>.aliases: A list of aliases for the command.  If not specified, it defaults to an empty list.

wccraft:
  enabled: true
  aliases:
    - "craft"

wcstonecutter:
  enabled: true
  aliases:
    - "cutter"

wcloom:
  enabled: true

wccartography:
  enabled: true
  aliases: 
    - "cartography"

wcfurnace:
  enabled: true
  aliases:
    - "smelt"

wcblastfurnace:
  enabled: true
  aliases:
    - "blast"

wcsmoker:
  enabled: true
  aliases:
    - "smoke"

wcsmithing:
  enabled: true
  aliases:
    - "smith"

wcanvil:
  enabled: true

wcenchant:
  enabled: true
  aliases:
    - "enchanting"

wcgrindstone:
  enabled: true
  aliases:
    - "grind"

wcbrew:
  enabled: true
  aliases:
    - "brew"